# Generated by Django 4.1.7 on 2023-04-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_data',
            old_name='image',
            new_name='img',
        ),
    ]
