# Generated by Django 4.1 on 2023-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_rename_image_url_data_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_data',
            name='link_counter',
            field=models.IntegerField(default=0),
        ),
    ]
