# Generated by Django 4.1 on 2023-04-03 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_url_data_link_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_data',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url_data',
            name='instance_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url_data',
            name='substrate_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
